### ISSUE TITLE
Switch version .hdf loading broken in 1.8.2

### ISSUE THREAD

**Issue by tomjramsden** [libretro/libretro-uae#193] opened 2019-12-28 12:29 UTC
When attempting to load a .hdf in switch version (1.8.2) stuck on kickstart loading screen. Kickstart Bios all set and using new whdload.hdf. Correct md5’s etc **This is working perfectly on the windows version of Retroarch** using the same config, Kickstarts, etc.

**Comment by rsn8887** [comment] 2019-12-28 13:51
I can reproduce this. The file handle is zero when loading hdf. It is this line of code that returns NULL: ```h = fopen (name, /*hfd->readonly ? "rb" :*/ "r+b");```

**Comment by rsn8887** [comment] 2019-12-28 14:18
Hmm I wonder if this ever worked on Switch.

**Comment by rsn8887** [comment] 2019-12-28 14:41
read-only works ("rb")

**Comment by rsn8887** [comment] 2019-12-28 15:29
It looks like the core is opening the hdf file multiple times for some reason and not closing the file properly. Needs some debugging. A r+b file should never be opened twice.

**Comment by rsn8887** [comment] 2019-12-28 16:35
Should be fixed with 4ea45cc9d52c16d268474999e653873a647c2fc8

Note that if you want to load hdf in read/write mode via `Load Content` on Switch, you have to ensure `Settings->File Browser->Automatically add content to playlists` is set to `OFF`. This is because the automatic scanner locks the file and prevents the Switch from opening it in read/write mode. This limitation does not seem to exist on other platforms.

**Closed by rsn8887** 2019-12-28 16:35 UTC
