### ISSUE TITLE
[For Reference] WHDLoad games that don't work with default settings.

### ISSUE THREAD

**Issue by ghost** [libretro/libretro-uae#231] opened 2020-01-28 22:13 UTC
Assuming the defaults being used are `Model: Automatic` and `CPU Compatibility: Normal`.

-----------------------------------------------------

**_AirSupport_v1.1_1320_**
Retroarch crash/blue screen after intro. Need to force model to A1200. (Note: **NTSC** version works with `Model: Automatic`).

**_Apidya_v2.05_**
**_ApidyaSpecialEdition_v1.1_Hack_by_Earok_**
Sprites go invisible at the top part of the screen. Need to force model to A1200.

**_DragonsLair_v1.2a_1360_**
Green or Black screen. Need to force model to A1200. (Note: **DragonsLair&EscapeFromSingesCastle** works with `Model: Automatic`).

**_Executioner_v1.1_**
Black screen. Need to force model to A1200.

**_Hostages_v1.2_0186_**
**_Hostage_v1.2_NTSC_1173_**
Get instantly shot. Needs '`Cycle Exact`'.

**_ItCameFromTheDesert_v2.0_0014_**
**_ItCameFromTheDesert2_v2.0_**
Lots of flicker in various places. Needs '`Cycle Exact`'.

**_NewYorkWarriors_v1.4_512KB_0705_**
**_NewYorkWarriors_v1.4_1MB_**
No sound effects. Needs '`Cycle Exact`' (or set CPU speed to -10%).

**_SensibleGolf_v1.2_0200_**
Going to the options will crash. Need to force model to A1200.

**_SensibleWorldOfSoccer_**
Career mode crashes after team selection. Needs '`Cycle Exact`'.

**Comment by i30817** [comment] 2020-01-30 21:07
Hey, isn't it better to assume that the default machine whdloads are going to be coded for is at least a A1200? Are there WHDLoad games that crash if they're not on a A500 with HD and aren't marked as such in the name?

BTW, some nonstandard hdfs are named 'AmigaCD' (wasted dreams for one), which in effect appears to be a conversion of one of the AGA machines with a cdrom to hdf only, so that 'AmigaCD' appears to be a sign to use a A1200 (or more).

Similarly there is a '_MT32' on some games which i don't know if UAE emulates (though libmt32 exists on the munt repo, and there is a patch for dosbox there as a example).

**Comment by sonninnos** [comment] 2020-01-31 20:53
Indeed, it is starting to look like Automatic should be A1200 on hardfiles. The reasoning for the current behavior is that there are some games that are for some reason too fast and/or glitchy with A1200, and therefore A600 is used by default when there is no `AGA` or `(A1200)` in the filename. (A500 does not boot from HD).

There exists an unofficial CD32 FastRAM collection which includes Wasted Dreams, and the core already supports CD32 with 8MB Fast, via model and via filename matching, so that is covered. And by my understanding only CD32 can boot from a CD, so getting AmigaCD games to work generally will require some trickery and tinkery in Amiga side anyway.

But if the CD is converted to an autobooting HDF then that should be simply covered now with the filename force tag. I guess there is no reason why `AmigaCD` should not be added to do the same as `AGA` and `(A1200)`.

Regular memory settings have no room to go at the moment, because anything over 8MB requires JIT, and that is not compiling. Settings for less than 8MB also is not of any use, except if savestate size is an issue.

UAE does not have any builtin MT32 stuff, but I guess it should be able to handle serial port MIDI like the real thing. No idea what needs to be done to hook it up to the RA MIDI support, and also very little interest in finding out (much more important things to be done). I do own a MT32, and have been planning to sometimes test those handful of games that is supposed to support it with a real Amiga.

**Comment by WindyWinston** [comment] 2020-01-31 21:26
To add to what sonninnos said -

I'd say on this core there are less glitches running WHDLoad ECS games on A600 than if you ran them on A1200. This would be different I think for WinUAE.

> There are also sometimes - in retroplay whdloads - substrings in the name for the required memory that libretro-uae doesn't recognize.

These are only for people with real Amigas who have limited Fast Ram etc. In emulation the more memory the better.

MT-32 is only for those lucky people like @sonninnos who have a real Roland sound module 😺

**Comment by sonninnos** [comment] 2020-01-31 22:29
> I'd say on this core there are less glitches running WHDLoad ECS games on A600 than if you ran them on A1200. This would be different I think for WinUAE.

So to be clear: You recommend we keep Automatic as it is for now? More hassle and effort in doing renaming exceptions or game specific core option CPU slowdown to force A600/ECS than A1200/AGA?

Surely if/when the accuracy ever gets better, things might change. Indeed I've been running everything in A1200 with WinUAE and had none of the running too fast & glitchy problems witnessed here. A few examples of those are: Flood, Hybris, PushOver. All run fine in A600 with this core.


> MT-32 is only for those lucky people like @sonninnos who have a real Roland sound module 
😺

Well Munt is pretty darn good these days, so it isn't impossible or far fetched to make it usable with this core, but the payoff is very minimal, since those Sierra games (what else can even benefit from a MT-32?) are better off with DOS anyway. Especially when it comes to emulation.

**Comment by i30817** [comment] 2020-01-31 23:41
Also thank you for fixing savestates (as much as they can possibly can be fixed on the flaky Amiga-with-harddrive environment). That was the main problem i had with fs-uae.

**Comment by i30817** [comment] 2020-03-21 14:37
**MurdersInSpace_v1.2_Files_2344** (not MurdersInSpace_v1.2_Image_2344) appears to crash with A600 down (the default) after the intro sequence of moving the shuttle. It passes that with the A1200, with a bit of flashing.

MurdersInSpace_v1.2_Image_2344 works on A600 (default) but apparently not on A500 or A1200

This game was recently updated: http://www.whdload.de/games/MurdersInSpace.html

**Comment by sonninnos** [comment] 2020-03-21 14:51
A500 does not have internal HD, therefore it will not work at all with any WHDLoad installs or harddrives.

Does the same symptoms happen with the current WinUAE? If yes, slave is to blame, if no, this old UAE is to blame.

**Comment by i30817** [comment] 2020-03-21 15:45
WinUAE doesn't boot whdload installs directly so i don't wanna bother. I did find a interesting thing, the rom required for the A600 in retroarch and winuae is different. WinUAE requires the A600**HD** rom. Not sure if on purpose.

**Comment by sonninnos** [comment] 2020-03-21 16:31
Sure, UAE does not directly play ball with WHDLoad, therefore this core simply generates a conf file that any UAE can use. Just take these rows from `puae_libretro.uae` in saves and add them (replace all other filesystems) to the conf file you use with WinUAE:
```
filesystem2=rw,WHDLoad:WHDLoad:"c:\\tools\\retroarch\\saves\\amiga\\WHDLoad",0
filesystem2=ro,DH0:LHA:"s:\\emu\\amiga\\lha\\Gods_v2.3.1_0666.lha",0
filesystem2=ro,RASystem:RASystem:"c:\\tools\\retroarch\\system",-128
filesystem2=rw,WHDSaves:WHDSaves:"c:\\tools\\retroarch\\saves\\amiga\\WHDSaves",-128
```

The A600HD Kickstart is 2.05, this is 3.1 for reasons I'm not exactly sure of, but because WHDLoad deals with only kick40063.A600 (not used at the moment, because all slaves that can use it can also use kick40068.A1200, which is mandatory anyway), then why not this core too.

**Comment by i30817** [comment] 2020-03-21 17:06
Since i'm using wine i had to change it to use the dx9 backend (i have a old graphics card) and turn off triple buffering to get anywhere (and the paths). I used the mount options (after the path) of the libretro boot of the game, and then it told me the WHDLoad volume was write protected, i'm going to load on libretro with a directory instead of a image for the whdload files and try again.

Annnd, the same thing happens with dirs for WHDLoad and WHDSaves (RASystem already was a dir)

**Comment by i30817** [comment] 2020-03-21 17:20
Yep, after increasing main memory from 1mb to 2mb in winaue it game the exact same error after the intro (it also flashed on transitions but i don't think it matters):

Winuae:
![image](https://user-images.githubusercontent.com/757900/77232258-dd953b80-6b97-11ea-8a26-629c371c999c.png)


Retroarch core:
![image](https://user-images.githubusercontent.com/757900/77232326-382e9780-6b98-11ea-891c-f7099ae56e8b.png)

**Comment by i30817** [comment] 2020-03-21 19:08
Where do i get the .whdl_register in this core?

**Comment by sonninnos** [comment] 2020-03-21 19:23
From WHDLoad docs:
> The name of the dump file is ".whdl_register", the default location is "PROGDIR:" but can be changed with the CoreDumpPath option. If a file with the same name already exists, the dump will be appended - otherwise a new file will be created. 

`CoreDumpPath` is set to temp `T:`, because otherwise the dumps would get written to the game image, which of course can't happen with read only LHAs and is not good for HDFs either, as some are so filled up to the brink that any more writes break the whole image.

Just change the path in RA/system/WHDLoad.prefs to something like `WHDSaves:` so it will be neatly under RA/saves, just like `SavePath`.

**Comment by i30817** [comment] 2020-03-21 19:26
Could you do it in the core defaults? I think it makes sense. Or is it a question of WHDSaves sometimes being a image file the reason why you didn't?

And 'T:' is a temp file folder right, but for the AmigaOS or the Host?

**Comment by sonninnos** [comment] 2020-03-21 19:29
I think I just explained why I won't change the default.

Of course T: is the temp for Amiga. WHDLoad runs inside the Amiga, not the host..

**Comment by i30817** [comment] 2020-03-22 06:09
That bug got fixed by CFOU.

**Comment by sonninnos** [comment] 2020-04-12 01:16
Found an interesting one: **ClownOMania_v1.3_2807** will halt at the intro with "Cycle-exact" and "More compatible". Very surprising for 68000 to do that. 68020 will also halt, but changing to "Normal" won't continue like 68000 does.

**Comment by sonninnos** [comment] 2020-04-13 19:28
Another one: **CrimeWave_v1.1** crashes WHDLoad with "Cycle-exact" and "More compatible" after copy protection. "Cycle-exact" does not crash with 68020 though.

**Comment by sonninnos** [comment] 2020-04-13 21:06
Dammit, apparently I was having a too hefty training workout in **DaleyThompsonsOlympicChallenge_v1.0_2Disk_0313**, because suddenly after the squats I was looking at:
![retroarch_2020_04_13_22_56_13_584](https://user-images.githubusercontent.com/45124675/79160966-5d06db00-7de3-11ea-9fd3-49a1a36e04ec.png)

Didn't test yet with other than the default settings, because the rest day shall not be disregarded.

**Comment by WindyWinston** [comment] 2020-04-13 22:25
This makes me wonder, is the Cycle Exact code complete ? I can't test right now but I'm sure those games with Cycle Exact issues would work on WinUAE with the same settings. Is it looking like `Compatibility: Normal` should be the default ? I can only think of one game at the moment that needs Cycle Exact and that's 'It came from the desert', (oh and I think the floppy version of Xenon 2 may need it).

**Comment by i30817** [comment] 2020-04-13 22:49
I wouldn't be that sure it works in winuae. After all, whdloads are assembly hacks, and complex ones to boot, that often want to 'widen' compatibility or add features. It's not unusual for them to be broken because it's only 3-6 people maintaining and creating whdloads and many of the old whdload installers were made by people that are 'retired' so they continue to be broken even after reports.

**Comment by sonninnos** [comment] 2020-04-13 23:38
The 68000 Cycle-exact is supposed to be pretty complete, but nothing ever is, and it certainly is more complete than the other CPUs. Cycle-exact was made the default because it had less problems with savestates. That may or may not be the case anymore after the libco removal, because I haven't experienced any savestate problems after that, even those that did happen with Cycle-exact before.

I do have contemplated that maybe "Normal" should be the default for at least 68020, but it would be rather complex to make it for only certain CPUs, so it is all or nothing. And these latest findings sure suggest that it may be the right choice with this current UAE version.

Whatever route hits the most nails by default is the way to go, so more vigilant testing is more than welcome! But when testing the CPU setting with savestates one needs to remember, that the setting will be saved to the state, and thus will on load override whatever the core option is.

Some of my savestate issues were caused by that, but I did not realize it at the time, because it triggered in the shadows. As you may have already realized, it is very random what happens when changing the CPU setting on-the-fly. Some games don't mind going from Normal to CE, but will mind going from CE to Normal, and some won't mind at all. After loading a state, everything seems fine until I go to core options and change some remaps or anything other than the CPU setting. At that instance of course the CPU core option will get updated too, and lottery dictates what happens next.

I tried to simply make the state loading refresh the settings right away, but that wasn't good either, so looks like this is how it is.

**Comment by WindyWinston** [comment] 2020-04-14 09:14
Just for fun I tried **ClownOMania** on WinUAE and it freezes at the 'Starbyte' screen when using 68000 (with or without Cycle Exact) but works with 68020 (with or without Cycle Exact) ! This is kinda the opposite of what this PUAE does ! This seems very strange.

Also on WinUAE, **Executioner** works on A1200 and Cycle Exact (CE has to be turned off on PUAE). **CrimeWave** behaves the same as PUAE.

I know Tony Willen said that 68020 Cycle Exact is a lot of guesswork because there's no documentation about it but it's probably a lot more mature now than this old PUAE. 

It is what it is.

**Comment by WindyWinston** [comment] 2020-04-25 16:14
Found a weird one, this game has no sound effects on (new) defaults -

**_NewYorkWarriors_v1.4_512KB_0705_**
**_NewYorkWarriors_v1.4_1MB_**

Needs `Cycle Exact`, but if you leave it on `Compatibility: Normal` and set `CPU speed` to -10% the sound effects work ? Must me a slave timing issue.

**Comment by sonninnos** [comment] 2020-04-25 17:47
Here's hoping that the list won't become longer this way around..

**Comment by WindyWinston** [comment] 2020-04-26 18:27
As most of these are slave related I reported a couple of these games to the head honchos to see what would happen (2 Valhalla's and Spaceball). He said he's fixed Spaceball in the next release version and for Valhalla he said 

> bug in kickstart emulation. Workaround ATM: rename kick40068.A1200 and kick40068.A4000 from devs:kickstarts

Not really sure what he means so don't know if they are going to be fixed or not. I may report a couple more if they react the same on WinUAE.

**Comment by i30817** [comment] 2020-04-26 20:28
I think he meant it's a 'whdload' itself fix.

**Comment by WindyWinston** [comment] 2020-04-27 11:20
@sonninnos 2 out of the 3 games I reported have now been fixed for 68000 so removed from the list. However, Valhalla requires `kick40063.A600` (and RTB) to be copied in the WHDLoad Files and the WHDLoad.hdf image will need to be made bigger otherwise it won't fit.

**Comment by i30817** [comment] 2020-04-27 11:27
I'm confused, wasn't the Amiga 600 already the default for the core if the filename doesn't mention A1200 or something?

**Comment by WindyWinston** [comment] 2020-04-27 11:47
Currently, the A600 ROM (`kick40063.A600`) is not copied to the WHDLoad files. I think the Kickemu (that the WHDLoad guys use) chose the A500 or A1200 rom.

@sonninnos 
Maybe the `kick40068.A4000` rom should also be added to the WHDLoad.hdf etc. as it is stated as a requirement here http://whdload.de/docs/en/need.html

**Comment by sonninnos** [comment] 2020-04-27 12:02
Kickstart for UAE is not the same thing as the Kickstart for WHDLoad. Same file sure, but different uses.

That A4000 surely won't be needed anywhere, but if that A600 one really helps with something then it should be added. But I don't want to increase the HDF size, since I'm wanting to get rid of it anyway, so maybe just ditch the 1.2 KS from autocopying, will it fit then..?

**Comment by WindyWinston** [comment] 2020-04-27 12:09
If you are thinking of getting rid of the `WHDLoad.hdf` then maybe just add all the required RTB files (that WHDLoad recommends) then people can manually copy them from the System directory to the Saves directory ?

**Comment by sonninnos** [comment] 2020-04-27 12:21
Sure why not, those will fit into any crack.

I'm not doing the HDF removal any time soon, which means I will be keeping them interchangeable/compatible for the time being. Of course it has been tempting to remove those KS copyings away from internal `startup-sequence` to the core when extracting the files, but this current method is doing the job well enough for now.

And while the hassle of editing and testing HDFs is annoying, it isn't that annoying when the coast is clear. Still rather pile up a little and wait if there are other changes ahoy while at it.

**Comment by WindyWinston** [comment] 2020-04-27 12:39
I just read on EAB that the game `RiseOfTheRobots_v1.4-B_1365` :expressionless: gives the same error on 68000 as the Valhalla games, so if he does the same thing to fix that and the other Valhalla game then they'll probably need the `kick40063.A600` rom as well.

**Comment by sonninnos** [comment] 2020-04-27 12:43
Surely that game can be just forced to A1200 and fuhgeddaboutit :F

**Comment by WindyWinston** [comment] 2020-04-27 12:52
lol, I had to try that RiseoftheRobots just for conformation! It does need to force A1200 but when running it it just goes straight to the readme, you have to manually select the .info file in the file requester for some reason. No biggie!

**Comment by sonninnos** [comment] 2020-04-27 12:59
That should happen only if the .slave is named differently than the .info.

**Comment by WindyWinston** [comment] 2020-04-27 13:11
Slave and .info are both named the same.

Anyway, 68000 fixes have just been posted to the WHDLoad.de site.

Rise of the Robots
Valhalla - Before the War
Bloodnet (hadn't tried that one. Not on the list)

I'll wait till tomorrow for Retroplay to do his thang.

**Comment by WindyWinston** [comment] 2020-04-27 15:49
Just tested. All 4 games now work on 68000 (ShitRobots, Bloodnet and 2 Valhalla's) but all require the `kick40063.A600` ROM and RTB.

**Comment by sonninnos** [comment] 2020-04-28 04:41
Just tried `RiseOfTheRobots_v1.4-C_1365` with the A600 files and it went straight to the game without the selector. I'll look at the HDF hassle soonish.

**Comment by WindyWinston** [comment] 2020-04-28 09:42
Yeah, the new version works correctly (not that it matters for that game!).

I just tried a 3mb HDF (FFS) and it fits all 5 roms and RTB's with about 374K spare.

**Comment by sonninnos** [comment] 2020-04-29 14:45
Lolwut, the latest slave does in fact still fail at the first run, but only if WHDLoad is in HDF-mode.. So something something disk access time related.

I went nuts and increased both HDFs to 4MB while at it.

**Comment by Dion-Guy** [comment] 2020-05-05 21:28
> Indeed I've been running everything in A1200 with WinUAE and had none of the running too fast & glitchy problems witnessed here. A few examples of those are: **Flood**, Hybris, PushOver. All run fine in A600 with this core.

Hi, firstly I just want to say how fantastic it is that P-UAE works so wonderfully well with many of my favourite Amiga games, and I really do appreciate all the time and hard work that has gone into it.

My reason for slightly gatecrashing this thread is that I've been trying most of the day to get a couple of WHDLoad games running, but hitting a dead end.  The games in question are the above quoted Flood, and also Bomb Jack Beer Edition.  These are the only 2 games I've tried so far that refuse to work and they have the same thing in common - both specify that they need the kick34005.a500 and kick34005.a500.rtb files.

I am using the latest version of the pre-installed WHDLoad LHA files supplied by Retroplay and the problem I keep running into is "DOS Error 205" and it not finding the rom.key, despite it being in RetroArch/System with the kickstarts.  I am running kick40068.a1200 kickstart with the Amiga 1200 2+8MB configuration, and lots of other games work fine, but not these 2.  I have tried the following files (plus the RTB file) in the RetroArch/System folder so far:

1. The (renamed to) 34005.a500 kickstart (512KB) and rom key I got from my purchase of the Amiga Forever Essentials pack.
2. An unencrypted 256KB 34005.a500 downloaded from the internet without the rom key (checksum matched).
3. An unecrypted 512KB 34005.a500 downloaded form the internet without the rom key.
4. Booting as the 1200 without any other kickstarts or rom key included (same results).
5. Booting as an A600 instead (using the 40063.a600 kickstart) and tried it with files as per 1, 2 and 3.

I've been at this for several hours and just can't figure out what I'm doing wrong.  I know you got Flood working but I'm not sure if the was Retroplay's pre-installed LHA archive or just an ADF.

Sorry this is such a long post.  Please can anyone offer any insight or help?

**Comment by sonninnos** [comment] 2020-05-05 22:13
Both of those work fine with the proper KS ROM mentioned in https://github.com/libretro/libretro-uae/blob/master/README.md

My hunch says the thing you're battling with is down to the file being wrong the first time around. Because the WHDLoad helper image copies `kick34005.A500` along with the others only if it is not found in the helper image. So make sure the MD5 is correct in `system` AND then delete the automatically generated WHDLoad-directory in `saves`, or only the offending KS inside.

The selected model and/or Kickstart in UAE does matter with what WHDLoad wants to emulate.   As in when a slave needs a certain Kickstart, the actually running Kickstart will not help. RTBs are already included in the image. No need to hassle with anything else except those mentioned in the README.

**Comment by Dion-Guy** [comment] 2020-05-06 07:11
> My hunch says the thing you're battling with is down to the file being wrong the first time around. Because the WHDLoad helper image copies `kick34005.A500` along with the others only if it is not found in the helper image. So make sure the MD5 is correct in `system` AND then delete the automatically generated WHDLoad-directory in `saves`, or only the offending KS inside.

You are completely right!  Many thanks for your help.  I hadn't realised that it copied across the first kick34005.a500 that I tried (the renamed 512KB one from Amiga Forever Essentials) to _saves_, and was then defaulting to that one no matter which one I put in _system_!  Once I followed your instructions and put the right one in _system_ and deleted the one in _saves_, both games worked perfectly.

I am very grateful for your help.  Thanks again for all your hard work on P-UAE - it's so great to be able to play these timeless games again on my TV (via Nvidia Shield).

**Closed** 2021-12-19 17:25 UTC
