### ISSUE TITLE
Feature Request & Bug Report: Android User, 1.9.6

### ISSUE THREAD

**Issue by EmpireFaust** [libretro/libretro-uae#443] opened 2021-07-24 18:05 UTC
First, the bug report (though the bug itself is not what ultimately drew me to post):
I had an entire library of good .adf files that were all set up with working .m3u's. All of this worked perfectly as of about six months ago, but it took me a while to get back to PUAE, so I can't say where it happened. But as of this week, none of those files work anymore, though nothing has changed except Retroarch. 

So now, that leads into the feature request: 
I was recommended by Google to try the prepackaged WHDLoad .lha library with PUAE instead.
I did this, and all but two of the .lha's I have tried worked perfectly. Super Street Fighter II' The New Challengers & Super Street Fighter II' Turbo both have a memory error when loaded into PUAE. They each need up to 1.5mb of slow RAM in addition to the embedded 2mb/8mb. I know this, specifically, because I tested with UAE4arm and added that extra 1.5mb of memory to an otherwise basic emulated 2mb/8mb A1200 and was successful with the un-lha'ed versions of those same files.

Please and thank you for all of your work, you're doing the Lord's work!

**Comment by sonninnos** [comment] 2021-07-24 20:23
I haven't had issues with M3Us, so please post the verbose log of an unsuccessful launch. Are the paths absolute or relative?

I'm getting just a black screen with WHDLoad version of New Challengers, but (luckily) the regular HD installed HDF version does work, but the WHDLoad versions of Turbo are launching fine with default settings. Only need to switch to CD32 pad to actually play it.

Adding bogomem isn't helping here though, as it should not, since AGA machines do not have slow RAM, and slow and fast can't really coexist. If it does help in emulation, then surely that is a fault of the emulation.

You can test it by creating `puae_libretro_global.uae` to `saves` and adding `bogomem_size=6` (2=0.5, 4=1, 6=1.5).

There are lists here in issues for known WHDLoad problem cases, and that situation most likely isn't going to change until and if a proper rebasing of a more current (Win)UAE gets done. The compatibility is already pretty good, and the ones that aren't working aren't exactly motivational showcase material..

**Comment by EmpireFaust** [comment] 2021-07-24 23:02
[ssf2turbo - retroarch__2021_07_24__18_50_39.log](https://github.com/libretro/libretro-uae/files/6873165/ssf2turbo.-.retroarch__2021_07_24__18_50_39.log)
[m3u error - retroarch__2021_07_24__18_58_36.log](https://github.com/libretro/libretro-uae/files/6873166/m3u.error.-.retroarch__2021_07_24__18_58_36.log)
![SSF2TNCAGA-210724-185355](https://user-images.githubusercontent.com/87910972/126882929-acd035e4-abd1-40a6-8b69-91eef5850f42.png)
![SSF2TAGA-210724-185059](https://user-images.githubusercontent.com/87910972/126882930-b8366d0c-1103-4206-be6f-91f5b67f19f4.png)
![Super Street Fighter II Turbo-210724-185913](https://user-images.githubusercontent.com/87910972/126882931-0f3942a5-a46c-4428-8629-c6549f14166d.png)
[ssf2tnc - retroarch__2021_07_24__18_53_28.log](https://github.com/libretro/libretro-uae/files/6873167/ssf2tnc.-.retroarch__2021_07_24__18_53_28.log)

There are my verbose logs for both problems

**Comment by sonninnos** [comment] 2021-07-25 00:06
These are working here:

`Super Street Fighter II - The New Challengers AGA.hdf`:
![retroarch_2021_07_25_03_04_05_383](https://user-images.githubusercontent.com/45124675/126883701-c81fbfc9-c293-4348-a6af-05115c5603ff.png)

`SuperStreetFighter2Turbo_v1.1_AGA_0735.lha`:
![retroarch_2021_07_25_02_58_16_888](https://user-images.githubusercontent.com/45124675/126883631-e838588d-fd8d-4369-85cf-2a8be1c10dd2.png)

And that M3U error is a CAPS library error, as in the disks are IPF, not ADF:
```
DLOPEN: dlopen failed: library "/storage/emulated/0/RetroArch/system/capsimg.so" needed or dlopened by "/data/data/com.retroarch.aarch64/cores/puae_libretro_android.so" is not accessible for the namespace "classloader-namespace"
DLOPEN: Failed to open /storage/emulated/0/RetroArch/system/capsimg.so
Unable to open capsimg.so
Failed to load CAPS plug-in.
This disk image needs the C.A.P.S. plugin which is available from http://www.softpres.org/download
```

The correct version of the library has to be in the executable directory in Android, and AFAIK that is only currently possible with rooting.

**Comment by EmpireFaust** [comment] 2021-07-25 00:56
[retroarch__2021_07_24__20_54_37.log](https://github.com/libretro/libretro-uae/files/6873227/retroarch__2021_07_24__20_54_37.log)
I assure you that it stalls out, also, with .adf m3u's, as seen here

**Comment by sonninnos** [comment] 2021-07-25 11:57
"Stalls out" how? Happens with all games/ADFs? The log reveals nothing odd except the amount of disks (11) which will not be fun juggling with the maximum of 4 drives even if it does work.



IPF version of New Challengers boots fine:
![retroarch_2021_07_25_14_42_57_568](https://user-images.githubusercontent.com/45124675/126897859-2e68b79d-e328-4a07-9b63-0584c28ecdd4.png)

But disk version of Turbo does not boot at all with any disk, since it requires hard disk installing, so that looks like your problem.

You need to enable "Global Boot HD" core option and install Workbench to be able to do HD installing:
![retroarch_2021_07_25_14_48_01_769](https://user-images.githubusercontent.com/45124675/126898001-ff990c4a-db85-4b10-adba-9be188292d8c.png)

![retroarch_2021_07_25_14_50_48_979](https://user-images.githubusercontent.com/45124675/126898005-7293f172-53d8-470d-81c7-623979bf2831.png)

![retroarch_2021_07_25_14_51_26_321](https://user-images.githubusercontent.com/45124675/126898008-b7a511df-95b9-4089-8fcf-e2067400bf54.png)


Or just try finding that pre-installed HDF version that I mentioned.

**Comment by EmpireFaust** [comment] 2021-07-25 23:16
I used the street fighter II variants as demonstratives because I had them all handy in the same place, but EVERY .adf anf .ipf that I have tried results in the "insert disk" bootup screen, for either A1200 or A500 depending on what the core detects the game needs. That's the thing: it clearly DETECTS the games, and I can use the "disc control" menu to swap them around, but I ALWAYS end up with a boot screen like you see in my last screenshot above.

**Comment by sonninnos** [comment] 2021-07-25 23:20
I just showed that Turbo is supposed to do that. It requires installing to HD and will not boot from floppies.

**Comment by EmpireFaust** [comment] 2021-07-25 23:30
[retroarch__2021_07_25__19_28_17.log](https://github.com/libretro/libretro-uae/files/6874701/retroarch__2021_07_25__19_28_17.log)
Here's an example of the problem using Battle Chess II, a fairly simple 2 .adf game.

**Comment by sonninnos** [comment] 2021-07-26 00:02
Log shows nothing weird and I have no problem running that particular game either.

**Comment by EmpireFaust** [comment] 2021-07-26 00:30
That's quite weird and leaves me with the feeling that my phone itself is to blame somehow. Strange.
And yeah, the preinstalled .hdf versions of both of the SSF2s actually work fine.

**Comment by sonninnos** [comment] 2021-07-26 00:59
The log says it parses the M3U fine though, so I have no idea where to begin.. Very likely again a random symptom caused by some random memory leak(s).

Test what happens when the core generates a M3U by putting all disks in a single ZIP/7z and launching it. The output will be in `saves/TEMP/` while the core is running, as in they are removed on exit.

**Comment by sonninnos** [comment] 2021-07-28 12:55
I found some ugliness in the M3U parsing parts, so please test if anything has changed.

**Closed** 2021-09-09 22:45 UTC
