### ISSUE TITLE
Gsync (50hz PAL) frametime stutters

### ISSUE THREAD

**Issue by WDeranged** [libretro/libretro-uae#641] opened 2023-12-23 18:30 UTC
I'm in love with P-UAE.  I stopped using WinUAE years ago due to the input latency and lack of advanced shaders.  Unfortunately under Retroarch (Windows 10) I'm getting frame pacing issues when running in Gsync.  If I force the refresh rate to 50hz using normal Vsync it's perfectly smooth but of course there is extra latency.

If this issue could be solved I'd be in CRT emulated Amiga paradise for the rest of my years and my real A600 could stay safely in its box.

**Comment by sonninnos** [comment] 2023-12-23 20:45
The core can't do or report the timing any better than what it already does. Your issue is elsewhere.

**Comment by WDeranged** [comment] 2023-12-24 00:22
Gsync works perfectly with my other cores.  It's also working properly in general.  No frame pacing issues in PC games.  There are a few Libretro cores that don't handle it well, Mesen and FB Alpha for example.  I get similar stutters with those cores unless I lock to 60hz standard vsync.

**Comment by sonninnos** [comment] 2023-12-24 11:44
Well whatever it is it can't be fixed by changing the core code, since the code already does what it can and should.

**Comment by WDeranged** [comment] 2023-12-24 14:08
I'm sure you're right.  Maybe my monitor just can't handle running so close to the lower limit of it's freesync implementation.  It should support 48~75Hz but it doesn't seem to like running at 50hz.

**Comment by sonninnos** [comment] 2024-02-09 01:31
I'll close this then since the core can't do this differently.

Can you reproduce the same issue with some other cores that are running at 50hz?

**Closed by sonninnos** 2024-02-09 01:31 UTC
Labels: invalid
