### ISSUE TITLE
Recent core from the updater crashes Retroarch when loading a game on Windows 10

### ISSUE THREAD

**Issue by Denshadego** [libretro/libretro-uae#613] opened 2023-06-03 00:29 UTC
From the last weeks, when updating the core on Windows 10, games no longer load and the Retroarch application crashes. Updating the core on android works normally.

Tested on default Retroarch config and core options and crashes still happen. Reverting to core version 4.9.1 ae58c0f for windows (latest stable) from the buildbot, makes the games load again.

Log:
[retroarch__2023_06_02__20_38_05.log](https://github.com/libretro/libretro-uae/files/11640046/retroarch__2023_06_02__20_38_05.log)

**Comment by sonninnos** [comment] 2023-06-03 00:32
I use Windows, so it is not that alone. Log does not show anything core related.

**Comment by Denshadego** [comment] 2023-06-03 00:34
Does it work for you? That would be weird, as the previous version mentioned works normally for me, but not when updating cores. How can I show more info in the log? RA instantly crashes when loading a game.

**Comment by sonninnos** [comment] 2023-06-03 00:36
Of course it works for me. I wouldn't push changes if it didn't. Log will catch core launches either way.

**Comment by Denshadego** [comment] 2023-06-03 00:57
I'm sorry, I was "thinking out loud", I figured it did by your answer.

Here's a log of trying to run a game after deleting retroarch.cfg and all contents of the Config folder, basically the same. 
[retroarch__2023_06_02__20_54_11.log](https://github.com/libretro/libretro-uae/files/11640086/retroarch__2023_06_02__20_54_11.log)

All cores work normally and the old version of the core does also. It may just be a random thing with my system then. Is there any way for me to provide better info?

**Comment by sonninnos** [comment] 2023-06-03 01:24
According to the log it isn't even starting the core, so no idea what could be the reason..

**Comment by Denshadego** [comment] 2023-06-03 03:38
Ok, did some further testing, even downloading a new RA installation. I have the RA folder in the root of my secondary drive (not C:), with the name "RetroArch", as I always have.

Games will only load for the newer versions of the core if I rename the RA folder. If, for example, I name it "RetroArchASDASD", games load regardless of method, playlist (portable) or by load content.

Games for other cores load fine with the original folder name, including the old version of PUAE. It only works that way for this core, pretty strange, haha. It doesn't have anything to do with saves or configs/core options, as I tested with those back to zero.

**Comment by sonninnos** [comment] 2023-06-03 11:53
Whaaat, that makes no sense whatsoever.. And looks like you started completely fresh, so it can't be `WHDLoad.prefs` in `system` and `WHDLoad` dir in `saves` either, which I was about to ask you to try delete also.

**Comment by Denshadego** [comment] 2023-06-03 22:02
I know, no sense at all, haha. Sadly I can't rename the folder because I sync various folders within it with the cloud, so I'll stick with the previous core version and check the newest once in a while to see if it works again for me.

Thank you for your time. I'll post and update if it gets fixed somehow.

**Comment by guestrr** [comment] 2023-06-05 13:03
I also had issues with the new core versions.
Config: Windows 11, vulkan, Navi 1.0 gpu, RA 1.15.0

Single WHDLoad game loaded fine the first time. Loading new content of any kind afterwards crashed Retroarch.
I managed to solve it (at least atm. it still works) by closing the content before loading anything new.
Since then it's loading new content again without closing the PUAE content.
Hope this helps a bit...

**Comment by Max-gee** [comment] 2023-06-05 23:38
had the same issue
Retroarch installed on C:\RetroArch-Win64
core will load but cant run content and even if i select "start core" without content selected it crashes retroarch 
older cores work fine happy to try other versions to confirm which commit is the cause
created a reddit post about the issue with logs here  
https://www.reddit.com/r/RetroArch/comments/13tgbe9/latest_amiga_core_no_longer_works_crash_even_with/

**Comment by sonninnos** [comment] 2023-06-06 00:09
I don't get it. This last log starts the emulation, but the OP log stops before starting UAE. I sure would like to fix whatever this is if I somehow could reproduce it. Could OP provide a debug level log of the crash?

**Comment by Denshadego** [comment] 2023-06-06 01:22
Both logs were at debug level, I did try again to the same results:
[retroarch__2023_06_05__21_21_31.log](https://github.com/libretro/libretro-uae/files/11658901/retroarch__2023_06_05__21_21_31.log)

However! I renamed the folder again, tried a game and it loaded, except that the whole application crashed when closing content, here's the log with more info:
[RENAMED_FOLDER_1_retroarch__2023_06_05__21_25_36.log](https://github.com/libretro/libretro-uae/files/11658906/RENAMED_FOLDER_1_retroarch__2023_06_05__21_25_36.log)

And, keeping the new name, launched another game, and just as before, Retroarch crashes before the game even loads:
[RENAMED_FOLDER_2_retroarch__2023_06_05__21_27_11.log](https://github.com/libretro/libretro-uae/files/11658909/RENAMED_FOLDER_2_retroarch__2023_06_05__21_27_11.log)

**Comment by sonninnos** [comment] 2023-06-06 15:57
Ok, I pushed a change that hopefully makes a difference.

**Comment by Max-gee** [comment] 2023-06-06 19:06
Hi Sonninnos,
progress shows good and bad news, good news is the core is no longer crashing on loading content and you can "start core" without issue 
however bad news is that it doesnnt seem to run content ok 
and i just get a gray screen with a back bar on the left hand side

**Comment by sonninnos** [comment] 2023-06-06 19:13
What content exactly, everything (floppies, hard drives, cds) in the same way? Here everything works just like before. And I can guess nothing without a log.

**Comment by Max-gee** [comment] 2023-06-06 19:15
Hi also looks like i spoke too soon, tried some other things and now with the 4.9.1 02ae3dc core ( presume this is your latest)  i get the same behaviour as before i.e. crashing when loading contect or even without content crash on "start core"  can provide  logs but they dont really seem to show much even when set to debug, any way to get more verbose detail from the logs ?

**Comment by sonninnos** [comment] 2023-06-06 19:19
No, https://github.com/libretro/libretro-uae/commit/951448c734c3bcdacb50b5b3190ce459aaa80477 is the latest, and only that tried to do something about this.

**Comment by Max-gee** [comment] 2023-06-06 19:25
that why i checked, first time i did the updater it gave me a core with the version starting with 9xxxx 
however now i cant seem to get that version again and its just giving me the 02ae3dc version I just did a new debug log but that will be for this other version how do i get your loaded again ?

**Comment by sonninnos** [comment] 2023-06-06 19:30
No reason to hassle with the old version log. Buildbot will offer the new one eventually.

**Comment by sonninnos** [comment] 2023-06-06 19:33
Updating info files is pointless in this case, but sure it should.

**Comment by Max-gee** [comment] 2023-06-06 19:38
ok cant explain how once it gave me the right 951448c version but now it will only give me your older commit. 
where can i download the updated puae_libretro.dll file manually so i can test it for you ?

**Comment by Max-gee** [comment] 2023-06-06 19:50
I found the nightlies at http://buildbot.libretro.com/nightly/windows/x86_64/latest/ but that version is also the older 02ae3dc version.   
apart from being able to compile your commits personally, how can I access the 951448c version with your changes ?

**Comment by sonninnos** [comment] 2023-06-06 19:58
That is where the program gets it so of course it is the same version. It will update eventually, just like before, so patience.

**Comment by Max-gee** [comment] 2023-06-06 20:27
ok understand, just need to wait, for buildbot to process the commits and it will compile a new DLL file, didnt know if there were other versions available "on demand" and for testing presume you have your own build machine setup to "roll your own" 
thanks for all your help, looking into this, will check again tomorrow

**Comment by Max-gee** [comment] 2023-06-07 10:14
So the build bot updated and i have loaded the new core 951448c
it doesnt crash but wont seem to load content it shows a gray frame on a black screen like an old CRT with timing issues 
![reetroarch amiga core](https://github.com/libretro/libretro-uae/assets/101988132/df60e326-de7e-4fb8-ae06-ee171ec449f3)

whats really odd is that earlier yesturday this was the same issue I saw (and commented on as below ) therefore retroarch must have downloaded your newer core, but subsequently reverted to an older version.  ( not that that matters now but at least I wasn't imaging things )

here is a log https://pastebin.com/LKmXDCvy

anyway anything you want me to test 

> Hi Sonninnos, progress shows good and bad news, good news is the core is no longer crashing on loading content and you can "start core" without issue however bad news is that it doesnnt seem to run content ok and i just get a gray screen with a back bar on the left hand side

**Comment by sonninnos** [comment] 2023-06-07 10:46
Ok, thanks. The log says on every core option row that "not implemented"..
```
[ERROR] [Environ]: GET_VARIABLE: puae_model - Not implemented.
```
So that is helpful and directly related to the earlier fix, and the solution looks very simple. So annoying that this does not happen for me, even though using pretty much as fresh version of RA, except self compiled, so it should be using the environ stuff exactly the same, but it does not.

**Comment by sonninnos** [comment] 2023-06-07 10:51
Next build ought to do it then.

**Comment by Max-gee** [comment] 2023-06-07 10:56
Any way to get the DLL to test it for you ?  Am heading to le man's tonight
for the 24h race so otherwise it won't be till next week

**Comment by sonninnos** [comment] 2023-06-07 11:01
[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/11676210/puae_libretro.zip)

**Comment by Max-gee** [comment] 2023-06-07 11:40
right some good progress with this version, no crashing and it's sort of working showing the CD32 Eyes screen "looking for bootable media" or the AROS prompt for Amiga content. 
see logs https://pastebin.com/XfukPUkY

However it wont run the content and also seems to complain that some kickstart roms aren't available ( optional ones like Kickstart ROM 'kick40068.A1200' not found!)

**Comment by sonninnos** [comment] 2023-06-07 11:51
Ok, so now only the paths are wrong/empty. If I allow setting of paths to happen on every `retro_set_environment` run, it will break the dynamic cartridge option. I already prevent it from happening after the paths are set, so this is really odd.

This must be some kind of a threading thing with the frontend, and the whole mess is caused by moving the setting of core options to `retro_set_environment`, where they ideally should be..

**Comment by Max-gee** [comment] 2023-06-07 12:04
Oh dear sounds like a bit of a dilemma, at least it may have helped uncover where the issues are, would it help to have a core that supports carts that could be distinct from the general use version ?

**Comment by sonninnos** [comment] 2023-06-07 12:08
Absolutely no such shenanigans. Try this: 
[puae_libretro.zip](https://github.com/libretro/libretro-uae/files/11676796/puae_libretro.zip)

**Comment by Max-gee** [comment] 2023-06-07 12:25
woohoo  no crashing, all working !  Amazing job, thank you for your time !
Content loads, no errors,  a500 and cd32 seem great! 
log here showing working https://pastebin.com/0P1PxT64

**Comment by sonninnos** [comment] 2023-06-07 12:29
Phew, thanks for confirming. Fix pushed.

**Comment by Max-gee** [comment] 2023-06-07 13:09
many thanks, i'll look out for a decent xenon2 as the audio that plays like  "bomb the bass" is an absolute classic & super nostalgic

**Comment by Denshadego** [comment] 2023-06-07 20:46
Hi!
Yesterday got to test the latest (at that time) core from the updater and the same happened to me, black screen with a grey frame flashing in irregularly. I just had deleted my retroarch.cfg, so I didn't get to log it and post to confirm it, but seems to have been the same problem.

Today updated again and now it works perfectly! Loading a game, closing content multiple times, works good again. Thank you for fixing it! Here's a log of the core working normally, if you want to check it:
[retroarch__2023_06_07__16_47_48.log](https://github.com/libretro/libretro-uae/files/11681811/retroarch__2023_06_07__16_47_48.log)

**Comment by sonninnos** [comment] 2023-06-07 21:56
Excellent, let's mark this as solved then.

**Closed by sonninnos** 2023-06-07 21:56 UTC
