### ISSUE TITLE
[Switch] setting 'WHDLoad support' to 'Files' crashes before starting the game

### ISSUE THREAD

**Issue by ms2048** [libretro/libretro-uae#360] opened 2020-12-21 23:32 UTC
I'm on RetroArch 1.9.0 on Nintendo Switch with newest core available from Core Updater (PUAE 2.6.1 e187a61).

When I try to open any .lha game with an option 'Media -> WHDLoad Support' set to 'Files', RetroArch crashes with 'The software was closed because an error occured'.

Fortunately, setting it to 'HDFs' works perfectly, though.

**Comment by sonninnos** [comment] 2020-12-26 15:49
Very odd, since the only difference between these baked files are that the included HDF images are gzipped and the Files-image is zipped. Because gzip only handles one file.

Please show the file list in `saves` (more importantly the `WHDLoad` directory which should be there in Files-mode). And also the innards of the file `puae_libretro.uae`. And a verbose log would be nice.

**Comment by ms2048** [comment] 2021-01-07 00:07
I'm attaching everything, just after a crash (log files have been generated a few minutes after all the other files, I forgot to turn logging on on a first attempt). These are from a 'complicated' configuration (I mean, I've been tinkering with this and don't really remember all the details) but I can do it again on a simpler one if necessary. Unfortunately, I cannot devote much time to this right now, so I am sorry for all the delays.

[filelist.txt](https://github.com/libretro/libretro-uae/files/5778746/filelist.txt)
[puae_libretro.uae.txt](https://github.com/libretro/libretro-uae/files/5778748/puae_libretro.uae.txt)
[retroarch__2021_01_07__01_01_06.log](https://github.com/libretro/libretro-uae/files/5778777/retroarch__2021_01_07__01_01_06.log)
[retroarch__2021_01_07__01_02_12.log](https://github.com/libretro/libretro-uae/files/5778778/retroarch__2021_01_07__01_02_12.log)
[retroarch__2021_01_07__01_02_56.log](https://github.com/libretro/libretro-uae/files/5778779/retroarch__2021_01_07__01_02_56.log)

**Comment by sonninnos** [comment] 2021-01-07 01:05
Hmm, according to filelist.txt only the first KS 1.2 is copied, which means it must crash right after it. Which makes very little sense. Some kind of write choking..? 

What happens if you manually copy the KS files from `system` to `saves/WHDLoad/Devs/Kickstarts`?

I could make the core copy them beforehand with the Files-mode though.

**Comment by ms2048** [comment] 2021-01-07 01:33
I have done so, including `kick40068.A1200` mentioned in the `puae_libretro.uae`. The crash occurred anyway.

It might have something to do with write choking though (or just crashing while writing?), as before I copied these files I saw that somehow two full kick* files were already there instead of just one (like in the `filelist.txt`)

**Comment by ms2048** [comment] 2021-01-07 01:34
... also, it is `savefiles` and not `saves`, just in case...

**Comment by sonninnos** [comment] 2021-01-07 05:31
The host filesystem is currently using low-level `open` & `read`/`write`/`lseek`. I've now managed to rewrite it using `fopen` & `fread`/`fwrite`/`fseek` instead.

The writing is happening in 64kb chunks, so hopefully those buffered functions help.

**Comment by sonninnos** [comment] 2021-01-09 21:37
Please delete the `WHDLoad` dir and try the current version.

**Comment by ms2048** [comment] 2021-01-10 03:54
I have deleted the directory but it still crashed. Most of the files have been recreated but not all:
- there was no `kick40068.A4000` despite `kick40068.A4000.RTB` being there
- the file `WHDLoad.prefs` from `S` got truncated to the first 1024 bytes

**Comment by sonninnos** [comment] 2021-01-10 04:24
Dangit. That 1024 thing sure is weird, but copying `kick40068.A4000` is skipped by design, because it is of no real use with WHDLoad, but the `.RTB` is there ready just in case it is added manually.

`WHDLoad.prefs` is full sized in `system` at least?

**Comment by ms2048** [comment] 2021-01-10 04:43
1935 bytes in `system/WHDLoad.prefs`

**Comment by sonninnos** [comment] 2021-01-28 09:28
I temporarily enabled verbose filesys logging for Switch on the next batch, so please try to get more data once it is merged, thanks.

The part after this block will be the useful one:
```
[libretro INFO] --------------------------------------------------------------------------------
[libretro INFO] PUAE 2.6.1 (0186c1b16f7181ffa02d73e6920d3180ce457c46)
[libretro INFO] Git commit: 8221e34
[libretro INFO] Build date: Jan 28 2021 11:13:00
[libretro INFO] 
[libretro INFO] See the source for a full list of contributors.
[libretro INFO] This is free software; see the file COPYING for copying conditions. There is NO
[libretro INFO] warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[libretro INFO] --------------------------------------------------------------------------------
```

**Comment by ms2048** [comment] 2021-01-30 04:44
I'm uploading the relevant part of the log below. The last lines there are related to the file `WHDLoad.prefs` from `S`, which is 1024 bytes long after the crash (as I've reported earlier) but the log still mentions 1935 bytes. So something is definitely wrong there...

[puae_log.txt](https://github.com/libretro/libretro-uae/files/5897386/puae_log.txt)

**Comment by sonninnos** [comment] 2021-01-30 14:18
Something weird but not definitive: File open flags are different, which makes no sense to me.

In your log it is `8602`:
```
[libretro INFO] my_open /retroarch/cores/savefiles/WHDLoad/S/WHDLoad.prefs flags=8602
```

In my log it is `8302`:
```
[libretro INFO] my_open c:\tools\retroarch\saves\amiga\WHDLoad/S/WHDLoad.prefs flags=8302
```

`0x8000` = O_BINARY
`0x0400` = O_EXCL
`0x0200` = O_TRUNC
`0x0100` = O_CREAT
`0x0002` = O_RDWR

That 600 should be then `O_EXCL | O_TRUNC`, but nowhere in the code is `O_EXCL` used, so uhh whut.. I'll soon test what happens in Linux.

The very next item in the log should be the file closing, which also flushes the data:
```
[libretro INFO] my_close (c:\tools\retroarch\saves\amiga\WHDLoad/S/WHDLoad.prefs)
```

**Comment by sonninnos** [comment] 2021-01-31 11:57
The next batch skips that section completely and does the file copying host-side before starting emulation. Will merge soon.

Which should leave us with the biggest suspense drama: Will in-game saves crash..?

**Comment by sonninnos** [comment] 2021-02-14 12:32
Sorry for rushing, but please try what happens with the current version.

**Comment by ms2048** [comment] 2021-02-14 18:46
With build b3efd9c it does not crash. Instead, its behavior is rather odd:
- with 'HDFs' enabled instead of 'Files' everything seems ok: the 'Workbench Screen' will pop up and after dismissing it via the 'Start' button the game will start; after quitting it with appropriate key it will display some readme text about the WHDLoad patch, its history, etc.
- with 'Files' selected (and every other option unchanged) this readme text is shown immediately, like after quitting it. After pressing 'Esc', some 'MkCustom' window pops up with 'no options' text and 'Cancel', 'Set', 'Remove' buttons...

Because of this, I am unable to test in-game saves, as I cannot get in-game...

**Comment by sonninnos** [comment] 2021-02-14 19:15
Progress of some sort then. Logs of the failing launch, or why not both, please..

Readme+MkCustom is launched always after quitting, and after that the startup loops. It can also be triggered before launching the slave by holding both fire buttons (Red+Blue).

**Comment by ms2048** [comment] 2021-02-14 21:14
Deleting the WHDLoad dir did not help. Logs attached.
[retroarch__2021_02_14__22_10_47.log](https://github.com/libretro/libretro-uae/files/5978538/retroarch__2021_02_14__22_10_47.log)
[retroarch__2021_02_14__22_11_14.log](https://github.com/libretro/libretro-uae/files/5978539/retroarch__2021_02_14__22_11_14.log)

**Comment by sonninnos** [comment] 2021-02-14 23:27
Indeed it all goes like it should for a while, but then suddenly it starts doing a saving operation which it totally should not. And then afterwards it no longer can access a file it was just reading:
```
[libretro INFO] my_fsize: stat on file '/retroarch/cores/savefiles/WHDLoad/S/Startup-Sequence' failed
[libretro INFO] 'S/Startup-Sequence' uniq=2 size=4294967295 seekpos=980 mode=0 dosmode=12
```
Nice size there..

Then I noticed you seem to have rewind enabled. That may very well be the cause of trouble.

**Comment by ms2048** [comment] 2021-02-15 06:00
For such a basic call as 'stat' to fail... it seems weird.

I disabled rewind and it didn't help. See the logs attached.
[retroarch__2021_02_15__06_45_15.log](https://github.com/libretro/libretro-uae/files/5979688/retroarch__2021_02_15__06_45_15.log)
[retroarch__2021_02_15__06_45_43.log](https://github.com/libretro/libretro-uae/files/5979689/retroarch__2021_02_15__06_45_43.log)

Also, rewind is kind of useful (and by that I mean 'a lot'! :) ) and it works fine with 'HDFs', so I really hope you wouldn't un-support it...

**Comment by sonninnos** [comment] 2021-02-15 11:07
Huh, no problems with HDF eh, even though savestates with HDFs are not at all supported in any UAE versions. Even WinUAE will alert the user when saving with them. Seems pure luck that the HDF files are not corrupted yet..

Though thanks to WHDLoad there isn't any disk access to the game data drive after the initial load in most cases, so if anything gets corrupted, it'll likely be WHDLoad.hdf, which can be recreated.



Something very weird in the log again:
```
[libretro INFO] fs_stat returned size         0: /retroarch/cores/savefiles/WHDLoad/C
```
Trying to get size of a directory..?

```
[libretro INFO] my_fsize: stat on file '/retroarch/cores/savefiles/WHDLoad/C/WHDLoad' failed
```
Surely that file should exist also.

**Comment by ms2048** [comment] 2021-02-15 13:10
Both exist and are very well :), and by that I mean readable. `WHDLoad` is 144902 bytes long.

**Comment by sonninnos** [comment] 2021-02-26 16:07
Had a crazy idea/hunch maybe worth trying, so please post the result of this:

1. Start once like usual so that it errs
2. Copy `saves/puae_libretro.uae` to `whatever.uae`
3. Edit `whatever.uae` and change the path of the WHDLoad row to something else like `WHDLoad_dir` instead. Change only the path inside the quotes, not the volume name.
4. Rename `WHDLoad` directory to `WHDLoad_dir`
5. Launch `whatever.uae`

**Comment by ms2048** [comment] 2021-02-28 16:20
The effect is the same (the readme gets displayed). Logs attached below; the last two should be from launching `whatever.uae`:

[retroarch__2021_02_28__16_49_47.log](https://github.com/libretro/libretro-uae/files/6057051/retroarch__2021_02_28__16_49_47.log)
[retroarch__2021_02_28__16_50_30.log](https://github.com/libretro/libretro-uae/files/6057054/retroarch__2021_02_28__16_50_30.log)
[retroarch__2021_02_28__16_52_51.log](https://github.com/libretro/libretro-uae/files/6057055/retroarch__2021_02_28__16_52_51.log)
[retroarch__2021_02_28__16_53_22.log](https://github.com/libretro/libretro-uae/files/6057057/retroarch__2021_02_28__16_53_22.log)

**Comment by sonninnos** [comment] 2021-03-01 04:31
Thanks. Since that `my_fsize` fails on the opened file, I changed the way the function gets the size. Please test what happens now.

**Comment by ms2048** [comment] 2021-03-01 15:03
Much better, it starts now! Logs attached below. I've played one game for a few minutes and all seems to be working; haven't tested saving (to hdd) yet though...

now, could you please explain whether the 'rewind' option and savestates in general are safe or not with 'Files' and 'HDFs'? What is the worst possible scenario there? I've been using them without problems before, so I am a little bit surprised. The only thing that I've noticed is that PUAE crashes after rewinding to the very beginning of the 'timeline' (both in 'Files' and 'HDFs' mode) but who needs that? Thank you!

[retroarch__2021_03_01__15_07_46.log](https://github.com/libretro/libretro-uae/files/6062404/retroarch__2021_03_01__15_07_46.log)
[retroarch__2021_03_01__15_08_17.log](https://github.com/libretro/libretro-uae/files/6062405/retroarch__2021_03_01__15_08_17.log)

**Comment by sonninnos** [comment] 2021-03-01 15:30
Wohoo, finally! I'll remove the verbose logging soon then, and this can be closed.

I don't know too much about the details of HDF, but the main wizard himself says it like this:

>Never use state files with HDFs because very quickly you run in situation where filesystem buffers inside statefile are out of sync with HDF data -> data corruption.
>Directory filesystem should work fine, even without preload because there is no Amiga side buffers. 


There are plenty of info about it out there (eab.abime.net). Of course the situation here in this core is not as bad, since there will be no writes to the game HDF, but only to the WHDLoad helper images.

Worst scenario is of course that the WHDSaves-image gets corrupted, since those can't be simply recreated. That rewind crash hasn't happened on my machines yet though..

**Comment by ms2048** [comment] 2021-03-01 16:09
So, now that 'Files' option is working, for sure this should be recommended then over 'HDFs'.

About that filesize detection: there is something to it. I'm using SX OS, where there is a builtin FTP server. When I'm connecting to it, it obviously reports filesizes, among other things. I've noticed that the reported size of the opened file is always wrong (at least when opened for writing and for random access (r+w), the reported size is instead 'copied' from some other file). After some other software closes the file, its filesize returns to normal. This would suggest that the similar error occurs inside the FTP server.

**Closed** 2021-03-04 00:41 UTC
Labels: help wanted
